### ISSUE TITLE
请问数据集咋下载啊？

### ISSUE THREAD

**Issue by ucas010** [sww9370/RoCBert#2]
hi大佬，数据集是git lfs version https://git-lfs.github.com/spec/v1
oid sha256:52bb388710662af0417b35f9c3db73e46ee0d5baf16848b22e64040eb9de3464
size 170844
这种形式的数据集咋下载啊？
也没搜到相关结果，给点提示呗，git lfs已经安装成功了。

**Comment by ucas010** [comment]
git lfs fetch
fetch: Fetching reference refs/heads/main
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/sww9370/RoCBert.git/info/lfs'

**Comment by sww9370** [comment]
train_data目录下的数据也可以在 https://huggingface.co/weiweishi/roc-bert-base-zh/tree/main 这里获取，这个目录下的数据是用于预训练初始时初始化一些参数的。
训练数据集我们目前不公开，你可以用已有的开源数据集进行训练

**Comment by ucas010** [comment]
数据集的形式呢？格式？

**Comment by sww9370** [comment]
https://github.com/sww9370/RoCBert/blob/main/dataset.py#L341  看预处理代码，每行一个query即可。
也可以根据自己的数据格式，参照https://github.com/sww9370/RoCBert/blob/main/dataset.py#L113 函数自行写dataset类
